Adding Python Random Generator app
iExecBlockchainComputing/iexec-dapps-registry pull request #123
Opened 2021-08-06 12:47 UTC by mcornaton

2021-08-26 10:17 UTC, PierreJeanjacquot requested changes
see comments

2021-08-26 10:17 UTC, PierreJeanjacquot commented on iExecBlockchainComputing/PythonRandomGenerator/iexec.json
> +    "multiaddr": "docker.io/mcornaton/python-random-generator:latest",
do not use latest tag

2021-08-26 10:17 UTC, PierreJeanjacquot commented on iExecBlockchainComputing/PythonRandomGenerator/iexec.json
> +    "tag": "0x0000000000000000000000000000000000000000000000000000000000000000",
if expected to run in tee enable tee tag "0x0000000000000000000000000000000000000000000000000000000000000001" if non tee this is fine

2021-08-26 10:17 UTC, PierreJeanjacquot commented on iExecBlockchainComputing/PythonRandomGenerator/iexec.json
> +    "multiaddr": "docker.io/mcornaton/python-random-generator:latest",
please push image on iexechub docker hub account

2021-08-26 10:17 UTC, PierreJeanjacquot commented on iExecBlockchainComputing/PythonRandomGenerator/iexec.json
> +    "mrenclave": "6660bd72614d91b25308bc6f20cbb00c0d3da8a60ccd5c72c0f03b5fe18f1d3f"
must be a standard V6 mrenclave (object or undefined)

2021-08-26 10:17 UTC, PierreJeanjacquot commented on iExecBlockchainComputing/PythonRandomGenerator/src/app.py
> +import json
sources are not required, this repo is not intended to store the source code.

2021-08-26 10:17 UTC, PierreJeanjacquot commented on iExecBlockchainComputing/PythonRandomGenerator/deployed.json
> +    "133": "0xa38e7b89d40503Bdf9dd7B87380886F01a5C8364"
the app must be published on the marketplace see `iexec orderbook app <address> [options]` result

2021-08-31 14:27 UTC, mcornaton commented
I close this pull request to submit a PR to v6 instead of v5. See there: https://github.com/iExecBlockchainComputing/iexec-dapps-registry/pull/124

2021-08-31 14:27 UTC, closed without merging