adding my nft-price-checker app
iExecBlockchainComputing/iexec-dapps-registry pull request #128
Opened 2022-06-02 15:23 UTC by mathisfchx

Here is the address of the bellecour deployed app : 0xe568E468495da3A2502EC6f6b5004144e2A65a51
Here are some viviani debug app (on v7 debug workepool) successfull tasks :
	args = "web2" : 0xc5acfa4ad5aa90f0f60c5c4c5b7bf3253ac34aad87aca733bbc075217b28576d
	args = "web3" : 0xb0b2edeed53f72283c29d2b0704636653fdbf3e73244efeb98d87ff36fed4bcc
And here is the orderHash of some "free" published apporder : 0x5ab21478ead12283f44035e3441beaa7ed3ed40c11eca9d831b917f7f7411d1c

2022-06-02 15:58 UTC, jeremyjams commented on mathisfchx/nft-price-checker/README.md
> +iexec app run --watch
Maybe you can add links and/or info of 2 successful tasks over here :)

2022-06-21 08:51 UTC, mathisfchx commented
Successful task on bellecour debug (with a new app 0x7C6620fB2e7bC883d5B834f8Cd6B9e62a069f0b0) : https://v7.core.debug-main-pool.bellecour.iex.ec/tasks/0xafed63aad70cdddc4fcd6dcb8e491a450d506a3dc5d433826e0dd763944d0d7d

2022-06-22 10:23 UTC, mathisfchx commented
✅  Successful task on bellecour prod (with a new sconified 5.7.2 prod image app 0xD037626C0F37a05eD8713242a61144f521fc4add) : https://v7.core.prod-main-pool.bellecour.iex.ec/tasks/0xbdffc5b7157daf129a85ad8bb363f2762924085fd837669749d5f5d6e0317df8

2022-06-27 15:26 UTC, PierreJeanjacquot requested changes
see comments + missing apporder for `0xD037626C0F37a05eD8713242a61144f521fc4add`

2022-06-27 15:26 UTC, PierreJeanjacquot commented on mathisfchx/nft-price-checker/iexec.json
> +    "tag": "0x0000000000000000000000000000000000000000000000000000000000000000",
```suggestion
    "tag": "0x0000000000000000000000000000000000000000000000000000000000000001",
```
use `tee` tag

2022-06-27 15:26 UTC, PierreJeanjacquot commented on mathisfchx/nft-price-checker/deployed.json
> +    "134": "0xe568E468495da3A2502EC6f6b5004144e2A65a51"
```suggestion
    "134": "0xD037626C0F37a05eD8713242a61144f521fc4add"
```
update app address?

2022-06-29 10:52 UTC, mathisfchx commented
Thanks for the comments @PierreJeanjacquot, +now the apporders are up !

2022-07-01 12:25 UTC, PierreJeanjacquot approved these changes

2022-07-01 12:26 UTC, merged